### ISSUE TITLE
aj-report 1.4.1 代码审计多处高危漏洞导致服务器权限丢失

### ISSUE THREAD

**Issue by unam4** [anji-plus/report#34]
详细看报告
[aj-report 二次就业.pdf](https://github.com/anji-plus/report/files/15363269/aj-report.pdf)

### 修复意见

接口健全确实，主要靠filter，一些重要的接口，权限缺失，如/dataSource、/dataSet下的接口，匿名用户也可以操作，filter建议直接使用getServletPath()，或者重写一下。

jwt的认证密钥是写在依赖包里面，无法修改.

返回包里面的DTO，把敏感字短执行加密。

**Comment by raodeming** [comment]
相关问题会在gitee后续跟进修复
