### ISSUE TITLE
Authentication Bypass vulnerability

### ISSUE THREAD

**Issue by S2eTo** [anji-plus/report#7]
这是英文的漏洞报告，中文的在(This is the English report, the Chinese report is in): [身份验证绕过漏洞](https://github.com/anji-plus/report/issues/8)

### Description

The program uses a fixed JWT key, and the stored Redis key uses username format characters. Any user who has logged in within an hour. JWT Token can be forged with his username to bypass authentication

Login API

*com.anjiplus.template.gaea.business.modules.accessuser.controller.AccessUserController#login*

![image-20221015111709407](https://user-images.githubusercontent.com/50647385/195968810-f6a32b3c-0d34-42aa-a0bd-7fa5c72bf01f.png)

Make redis key of format username, Although uuid is used, uuid is not involved in authentication.

*com.anjiplus.template.gaea.business.modules.accessuser.service.impl.AccessUserServiceImpl#login*

*com.anjiplus.template.gaea.business.constant.BusinessConstant#GAEA_SECURITY_LOGIN_TOKEN*

![image-20221015112014779](https://user-images.githubusercontent.com/50647385/195968818-26ea6c08-62d6-4d9d-944d-c4c8d22954d5.png)

Uses a fixed JWT secret key

*spring-boot-gaea-2.0.5.RELEASE.jar!com.anji.plus.gaea.utils.JwtBean#createToken*

*spring-boot-gaea-2.0.5.RELEASE.jar!com.anji.plus.gaea.GaeaProperties.Security#getJwtSecret*

![image-20221015112804990](https://user-images.githubusercontent.com/50647385/195968822-9eba4077-03c7-48e6-a5b6-915d800d3c95.png)

TokenFilter for authentication

*com.anjiplus.template.gaea.business.filter.TokenFilter#doFilter*

![image-20221015113222257](https://user-images.githubusercontent.com/50647385/195968829-ecab999a-c9c1-4304-97ab-f446f693c5f7.png)

Forge different users' Tokens by modifying the username field

```
{
    "type": 0,
    "uuid": "",
    "tenant": "tenantCode",
    "username": "admin"
}
```
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjowLCJ1dWlkIjoiIiwidGVuYW50IjoidGVuYW50Q29kZSIsInVzZXJuYW1lIjoiYWRtaW4ifQ.ce3xqqUypEinA_ZCSky9AptKjkG8qFm8ESMuCunqe6Y
```
![image-20221015122659078](https://user-images.githubusercontent.com/50647385/195968832-03cd4cef-06ba-4b0d-a7c5-7d7a7e196580.png)

**Comment by raodeming** [comment]
gitee跟踪，已修复
